# コメント制限設定（YAML形式）

# 地域特性による制限
regional_restrictions:
  prefecture_patterns:
    沖縄:
      forbidden_keywords:
        - "雪"
        - "雪景色" 
        - "粉雪"
        - "新雪"
        - "雪かき"
        - "雪道"
        - "雪が降る"
        - "極寒"
        - "凍える"
        - "凍結"
        - "防寒対策必須"
    北海道:
      forbidden_keywords:
        - "酷暑"
        - "猛暑"
        - "危険な暑さ"
        - "熱帯夜"

# 天気状況による制限
weather_restrictions:
  rain:
    weather_comment_forbidden:
      - "青空"
      - "晴れ"
      - "快晴"
      - "日差し"
      - "太陽"
      - "陽射し"
      - "眩しい"
      - "穏やか"
      - "過ごしやすい"
      - "快適"
      - "爽やか"
      - "心地良い"
      - "のどか"
      - "お出かけ日和"
      - "散歩日和"
      - "ピクニック"
      - "外出推奨"
      - "スッキリ"
      - "気持ちいい"
      - "清々しい"
      - "中休み"
      - "晴れ間"
      - "回復"
      - "一時的な晴れ"
      - "梅雨の中休み"
      - "梅雨明け"
      - "からっと"
      - "さっぱり"
      - "乾燥"
      - "湿度低下"
    advice_forbidden:
      - "日焼け止め"
      - "帽子"
      - "サングラス"
      - "日傘"
      - "紫外線"
      - "お出かけ"
      - "外出"
      - "散歩"
      - "ピクニック"
      - "日光浴"
      - "過ごしやすい"
      - "快適"
      - "心地良い"
      - "爽やか"
      - "洗濯物を外に"
      - "布団を干す"
      - "外干しを"
      - "窓を開けて"
      - "ベランダ作業"

  heavy_rain:
    weather_comment_forbidden:
      # rain + 追加制限
      - "にわか雨"
      - "ニワカ雨"
      - "変わりやすい"
      - "スッキリしない"
      - "蒸し暑い"
      - "厳しい暑さ"
      - "体感"
      - "心地"
      - "雲の多い"
      - "どんより"
      - "じめじめ"
      - "湿っぽい"
    advice_forbidden:
      # rain + 追加制限
      - "折り畳み傘"
      - "軽い雨具"
      - "短時間の外出"

  sunny:
    weather_comment_forbidden:
      - "雨"
      - "じめじめ"
      - "湿った"
      - "どんより"
      - "曇り"
      - "雲が厚い"
      - "傘"
      - "雨具"
      - "濡れ"
      - "湿気"
      - "降水"
    advice_forbidden:
      - "傘"
      - "レインコート"
      - "濡れ"
      - "雨具"
      - "長靴"

  cloudy:
    weather_comment_forbidden:
      - "青空"
      - "快晴"
      - "眩しい"
      - "強い日差し"
      - "ギラギラ"
      - "洗濯日和"
      - "布団干し日和"
      - "外干し"
      - "窓を開けて"
      - "ベランダで"
    advice_forbidden:
      - "強い日差し対策"
      - "紫外線対策必須"

# 気温による制限
temperature_restrictions:
  hot_weather:  # 30°C以上
    threshold: 30.0
    forbidden_keywords:
      - "寒い"
      - "冷える"
      - "肌寒い"
      - "防寒"
      - "暖かく"
      - "厚着"
  
  cold_weather:  # 12°C未満
    threshold: 12.0
    forbidden_keywords:
      - "暑い"
      - "猛暑"
      - "酷暑"
      - "熱中症"
      - "クーラー"
      - "冷房"
  
  mild_weather:  # 10-30°C
    forbidden_keywords:
      - "極寒"
      - "凍える"
      - "猛暑"
      - "酷暑"

# 湿度による制限
humidity_restrictions:
  high_humidity:  # 80%以上
    threshold: 80.0
    forbidden_keywords:
      - "乾燥注意"
      - "乾燥対策"
      - "乾燥しやすい"
      - "乾燥した空気"
      - "からっと"
      - "さっぱり"
      - "湿度低下"
  
  low_humidity:  # 30%未満
    threshold: 30.0
    forbidden_keywords:
      - "除湿対策"
      - "除湿"
      - "ジメジメ"
      - "湿気対策"
      - "湿っぽい"

# 悪天候時の必須キーワード
required_keywords:
  heavy_rain:
    weather_comment:
      - "注意"
      - "警戒" 
      - "危険"
      - "荒れ"
      - "激しい"
      - "強い"
      - "本格的"
    advice:
      - "傘"
      - "雨具"
      - "安全"
      - "注意"
      - "室内"
      - "控え"
      - "警戒"
      - "備え"
      - "準備"
  
  storm:
    weather_comment:
      - "嵐"
      - "暴風"
      - "警戒"
      - "危険"
      - "荒天"
      - "大荒れ"
    advice:
      - "危険"
      - "外出控え"
      - "安全確保"
      - "警戒"
      - "室内"
      - "備え"
      - "準備"