# NGワード設定ファイル
# コメント生成時に使用を避けるべき単語のリスト

ng_words:
  # 災害・危険関連
  - 災害
  - 危険
  - 注意
  - 警告
  - 警戒
  - 緊急
  
  # 断定的表現
  - 絶対
  - 必ず
  - 間違いない
  - 確実
  
  # 不適切な表現
  - くそ
  - やばい
  - 最悪
  - ひどい
  - 死ぬ
  - 殺す
  
  # 過度な表現
  - 超
  - めちゃくちゃ
  - すごく
  - とても