# 天気コメント検証ルール設定
# このファイルで天気条件に基づくコメントの適切性を定義します

# 天気別禁止ワード
weather_forbidden_words:
  # 雨天時（全レベル）
  rain:
    weather_comment:
      - "青空"
      - "晴れ" 
      - "快晴"
      - "日差し"
      - "太陽"
      - "陽射し"
      - "眩しい"
      - "穏やか"
      - "過ごしやすい"
      - "快適"
      - "爽やか"
      - "心地良い"
      - "のどか"
      - "お出かけ日和"
      - "散歩日和"
      - "ピクニック"
      - "外出推奨"
      - "スッキリ"
      - "気持ちいい"
      - "清々しい"
      - "中休み"
      - "晴れ間"
      - "回復"
      - "一時的な晴れ"
      - "梅雨の中休み"
      - "梅雨明け"
      - "からっと"
      - "さっぱり"
      - "乾燥"
      - "湿度低下"
    advice:
      - "日焼け止め"
      - "帽子"
      - "サングラス"
      - "日傘"
      - "紫外線"
      - "お出かけ"
      - "外出"
      - "散歩"
      - "ピクニック"
      - "日光浴"
      - "過ごしやすい"
      - "快適"
      - "心地良い"
      - "爽やか"
      - "洗濯物を外に"
      - "布団を干す"
      - "外干しを"
      - "窓を開けて"
      - "ベランダ作業"
  
  # 大雨・豪雨・嵐
  heavy_rain:
    weather_comment:
      - "青空"
      - "晴れ"
      - "快晴"
      - "日差し"
      - "太陽"
      - "陽射し"
      - "眩しい"
      - "穏やか"
      - "過ごしやすい"
      - "快適"
      - "爽やか"
      - "心地良い"
      - "のどか"
      - "お出かけ日和"
      - "散歩日和"
      - "ピクニック"
      - "外出推奨"
      - "スッキリ"
      - "気持ちいい"
      - "清々しい"
      - "にわか雨"
      - "ニワカ雨"
      - "変わりやすい"
      - "スッキリしない"
      - "蒸し暑い"
      - "厳しい暑さ"
      - "体感"
      - "心地"
      - "雲の多い"
      - "どんより"
      - "じめじめ"
      - "湿っぽい"
      - "中休み"
      - "晴れ間"
      - "回復"
      - "一時的な晴れ"
      - "梅雨の中休み"
      - "梅雨明け"
      - "からっと"
      - "さっぱり"
      - "乾燥"
      - "湿度低下"
    advice:
      - "日焼け止め"
      - "帽子"
      - "サングラス"
      - "日傘"
      - "紫外線"
      - "お出かけ"
      - "外出"
      - "散歩"
      - "ピクニック"
      - "日光浴"
      - "過ごしやすい"
      - "快適"
      - "心地良い"
      - "爽やか"
      - "折り畳み傘"
      - "軽い雨具"
      - "短時間の外出"
  
  # 晴天時
  sunny:
    weather_comment:
      - "雨"
      - "じめじめ"
      - "湿った"
      - "どんより"
      - "曇り"
      - "雲が厚い"
      - "傘"
      - "雨具"
      - "濡れ"
      - "湿気"
      - "降水"
    advice:
      - "傘"
      - "レインコート"
      - "濡れ"
      - "雨具"
      - "長靴"
  
  # 曇天時
  cloudy:
    weather_comment:
      - "青空"
      - "快晴"
      - "眩しい"
      - "強い日差し"
      - "ギラギラ"
      - "洗濯日和"
      - "布団干し日和"
      - "外干し"
      - "窓を開けて"
      - "ベランダで"
    advice:
      - "強い日差し対策"
      - "紫外線対策必須"

# 温度別禁止ワード
temperature_forbidden_words:
  hot:  # 30°C以上
    forbidden:
      - "寒い"
      - "冷える"
      - "肌寒い"
      - "防寒"
      - "暖かく"
      - "厚着"
  cold:  # 12°C未満
    forbidden:
      - "暑い"
      - "猛暑"
      - "酷暑"
      - "熱中症"
      - "クーラー"
      - "冷房"
  mild:  # 10-30°C
    forbidden:
      - "極寒"
      - "凍える"
      - "猛暑"
      - "酷暑"

# 必須キーワード（悪天候時）
required_keywords:
  heavy_rain:
    weather_comment:
      - "注意"
      - "警戒"
      - "危険"
      - "荒れ"
      - "激しい"
      - "強い"
      - "本格的"
    advice:
      - "傘"
      - "雨具"
      - "安全"
      - "注意"
      - "室内"
      - "控え"
      - "警戒"
      - "備え"
      - "準備"
  storm:
    weather_comment:
      - "嵐"
      - "暴風"
      - "警戒"
      - "危険"
      - "荒天"
      - "大荒れ"
    advice:
      - "危険"
      - "外出控え"
      - "安全確保"
      - "警戒"
      - "室内"
      - "備え"
      - "準備"

# 地域別NG表現
regional_ng_expressions:
  沖縄:
    inappropriate:
      - "雪"
      - "凍結"
      - "氷点下"
      - "霜"
      - "初雪"
      - "スキー"
      - "スノーボード"
  北海道:
    inappropriate_summer:  # 夏季（6-8月）
      - "猛暑日"
      - "熱帯夜"
      - "酷暑"
      - "35度超え"

# 湿度別禁止ワード
humidity_forbidden_words:
  high:  # 80%以上
    forbidden:
      - "乾燥"
      - "カラカラ"
      - "パサパサ"
      - "サラサラ"
      - "爽やか"
  low:  # 30%未満
    forbidden:
      - "じめじめ"
      - "湿っぽい"
      - "ムシムシ"
      - "蒸し暑い"

# 閾値設定
thresholds:
  temperature:
    hot: 30
    cold: 12
    mild_min: 10
    mild_max: 30
  humidity:
    high: 80
    low: 30
  precipitation:
    light: 3.0
    moderate: 10.0
    heavy: 20.0
    very_heavy: 50.0
  thunder:
    light_threshold: 5.0  # 軽微な雷の降水量閾値

# 過度な警戒表現（軽い雨で禁止）
excessive_warning_words:
  weather_comment:
    - "激しい"
    - "警戒"
    - "危険"
    - "大荒れ"
    - "本格的"
    - "強雨"
  advice:
    - "避難"
    - "危険"
    - "中止"
    - "延期"
    - "控える"