"""
天気条件別の禁止ワード設定

このファイルは、天気条件に基づいてコメントで使用すべきでない
単語やフレーズを定義します。
"""

# 雨天時（全レベル）の禁止ワード
rain:
  weather_comment:
    - 青空
    - 晴れ
    - 快晴
    - 日差し
    - 太陽
    - 陽射し
    - 眩しい
    - 穏やか
    - 過ごしやすい
    - 快適
    - 爽やか
    - 心地良い
    - のどか
    - お出かけ日和
    - 散歩日和
    - ピクニック
    - 外出推奨
    - スッキリ
    - 気持ちいい
    - 清々しい
    # 雨天時に矛盾する表現
    - 中休み
    - 晴れ間
    - 回復
    - 一時的な晴れ
    - 梅雨の中休み
    - 梅雨明け
    - からっと
    - さっぱり
    - 乾燥
    - 湿度低下
  advice:
    - 日焼け止め
    - 帽子
    - サングラス
    - 日傘
    - 紫外線
    - お出かけ
    - 外出
    - 散歩
    - ピクニック
    - 日光浴
    - 過ごしやすい
    - 快適
    - 心地良い
    - 爽やか
    # 雨天時の生活関連アドバイス
    - 洗濯物を外に
    - 布団を干す
    - 外干しを
    - 窓を開けて
    - ベランダ作業

# 大雨・豪雨・嵐の禁止ワード
heavy_rain:
  weather_comment:
    # 雨天時の禁止ワード全て
    - 青空
    - 晴れ
    - 快晴
    - 日差し
    - 太陽
    - 陽射し
    - 眩しい
    - 穏やか
    - 過ごしやすい
    - 快適
    - 爽やか
    - 心地良い
    - のどか
    - お出かけ日和
    - 散歩日和
    - ピクニック
    - 外出推奨
    - スッキリ
    - 気持ちいい
    - 清々しい
    # 軽微な表現（大雨時は特に禁止）
    - にわか雨
    - ニワカ雨
    - 変わりやすい
    - スッキリしない
    - 蒸し暑い
    - 厳しい暑さ
    - 体感
    - 心地
    - 雲の多い
    - どんより
    - じめじめ
    - 湿っぽい
    # 大雨時に特に不適切な表現
    - 中休み
    - 晴れ間
    - 回復
    - 一時的な晴れ
    - 梅雨の中休み
    - 梅雨明け
    - からっと
    - さっぱり
    - 乾燥
    - 湿度低下
  advice:
    # 基本的な外出系
    - 日焼け止め
    - 帽子
    - サングラス
    - 日傘
    - 紫外線
    - お出かけ
    - 外出
    - 散歩
    - ピクニック
    - 日光浴
    - 過ごしやすい
    - 快適
    - 心地良い
    - 爽やか
    # 軽い対策（大雨時は不適切）
    - 折り畳み傘
    - 軽い雨具
    - 短時間の外出

# 晴天時の禁止ワード
sunny:
  weather_comment:
    - 雨
    - じめじめ
    - 湿った
    - どんより
    - 曇り
    - 雲が厚い
    - 傘
    - 雨具
    - 濡れ
    - 湿気
    - 降水
    # 晴天時に不適切な空の状態表現
    - スッキリしない
    - すっきりしない
    - はっきりしない
    - ぼんやり
    - もやもや
    - 重い空
    - 厚い雲
    - 灰色の空
    - 曇りがち
    - 雲多め
    - 変わりやすい天気
    - 不安定
    # 安定した晴れ天気に不適切な表現
    - 変わりやすい空
    - 変わりやすい
    - 気まぐれ
    - 移ろいやすい
    - 一定しない
    - 変化しやすい
    - 変動
    - 不規則
  advice:
    - 傘
    - レインコート
    - 濡れ
    - 雨具
    - 長靴

# 曇天時の禁止ワード
cloudy:
  weather_comment:
    - 青空
    - 快晴
    - 眩しい
    - 強い日差し
    - ギラギラ
    # 雨天時の生活関連表現
    - 洗濯日和
    - 布団干し日和
    - 外干し
    - 窓を開けて
    - ベランダで
  advice:
    - 強い日差し対策
    - 紫外線対策必須