name: Validate Location Data

on:
  push:
    paths:
      - 'src/data/location_coordinates.csv'
      - 'src/data/Chiten.csv'
      - 'data/Chiten.csv'
      - 'src/ui/components/location_selector.py'
      - '.github/workflows/validate-location-data.yml'
  pull_request:
    paths:
      - 'src/data/location_coordinates.csv'
      - 'src/data/Chiten.csv'
      - 'data/Chiten.csv'
      - 'src/ui/components/location_selector.py'
      - '.github/workflows/validate-location-data.yml'

jobs:
  validate-locations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Copy validation script
      run: |
        if [ -f "scripts/validate_location_data.py" ]; then
          cp scripts/validate_location_data.py validate_location_data.py
        else
          echo "エラー: scripts/validate_location_data.py が見つかりません"
          exit 1
        fi
    
    - name: Run Python validation
      run: python validate_location_data.py
    
    - name: Summary
      if: always()
      run: |
        echo "=== Location Data Validation Summary ==="
        echo "Expected location count: 142"
        echo "Check the output above for validation results"